###### CLICKSTREAM TAGGING CONFIGURATION #######


 curl -X POST -H "Content-Type: application/json" --data '{"name":"staging-awslambda-requesttagging","config":{"connector.class":"io.confluent.connect.aws.lambda.AwsLambdaSinkConnector","tasks.max":"1","topics":"socket_visitorjourney_visitor_page_visit","aws.lambda.function.name":"arn:aws:lambda:eu-west-1:420021094716:function:CP-ClickstreamTagging-staging-tagRequest","aws.lambda.invocation.type":"sync","aws.lambda.batch.size":"1","behavior.on.error":"fail","key.converter":"org.apache.kafka.connect.storage.StringConverter","value.converter":"org.apache.kafka.connect.storage.StringConverter","value.converter.schemas.enable":"false","confluent.topic.bootstrap.servers":"SASL_SSL://pkc-43n2o.eu-west-1.aws.confluent.cloud:9092","confluent.topic.replication.factor":"1","confluent.topic.ssl.endpoint.identification.algorithm":"https","confluent.topic.sasl.mechanism":"PLAIN","confluent.topic.request.timeout.ms":20000,"confluent.topic.retry.backoff.ms":500,"confluent.topic.sasl.jaas.config":"org.apache.kafka.common.security.plain.PlainLoginModule required username=\"USERNAME\" password=\"PASSWORD\";","confluent.topic.security.protocol":"SASL_SSL","aws.lambda.response.topic":"clickstream_tagging_request_tagged","aws.lambda.response.bootstrap.servers":"SASL_SSL://pkc-43n2o.eu-west-1.aws.confluent.cloud:9092","aws.lambda.response.replication.factor":"1","aws.lambda.response.ssl.endpoint.identification.algorithm":"https","aws.lambda.response.sasl.mechanism":"PLAIN","aws.lambda.response.request.timeout.ms":20000,"aws.lambda.response.retry.backoff.ms":500,"aws.lambda.response.sasl.jaas.config":"org.apache.kafka.common.security.plain.PlainLoginModule required username=\"USERNAME\" password=\"PASSWORD\";","aws.lambda.response.security.protocol":"SASL_SSL"}}' http://internal-staging-confluent-internal-1490939931.eu-west-1.elb.amazonaws.com:8083/connectors/

curl -X GET http://internal-staging-confluent-internal-1490939931.eu-west-1.elb.amazonaws.com:8083/connectors/staging-awslambda-requesttagging/status

curl -X DELETE http://internal-staging-confluent-internal-1490939931.eu-west-1.elb.amazonaws.com:8083/connectors/staging-awslambda-requesttagging/

