// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AO.SCV.MessagingEngine.Events.Schemas
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using global::Avro;
    using global::Avro.Specific;

    public partial class Conversion : ISpecificRecord
    {
        public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"Conversion\",\"namespace\":\" AO.SCV.MessagingEngine.Events." +
                                                    "Schemas\",\"fields\":[{\"name\":\"convertedTimeStamp\",\"type\":[\"long\",\"null\"]},{\"name\":" +
                                                    "\"orderNumber\",\"type\":[\"string\",\"null\"]}]}");
        private System.Nullable<long> _convertedTimeStamp;
        private string _orderNumber;
        public virtual Schema Schema
        {
            get
            {
                return Conversion._SCHEMA;
            }
        }
        public System.Nullable<long> convertedTimeStamp
        {
            get
            {
                return this._convertedTimeStamp;
            }
            set
            {
                this._convertedTimeStamp = value;
            }
        }
        public string orderNumber
        {
            get
            {
                return this._orderNumber;
            }
            set
            {
                this._orderNumber = value;
            }
        }
        public virtual object Get(int fieldPos)
        {
            switch (fieldPos)
            {
                case 0: return this.convertedTimeStamp;
                case 1: return this.orderNumber;
                default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
            };
        }
        public virtual void Put(int fieldPos, object fieldValue)
        {
            switch (fieldPos)
            {
                case 0: this.convertedTimeStamp = (System.Nullable<long>)fieldValue; break;
                case 1: this.orderNumber = (System.String)fieldValue; break;
                default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
            };
        }
    }
}