// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AO.SCV.MessagingEngine.Events.Schemas
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;

	public partial class MessagingResult : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""MessagingResult"",""namespace"":"" AO.SCV.MessagingEngine.Events.Schemas"",""fields"":[{""name"":""visitorId"",""type"":""string""},{""name"":""messageId"",""type"":[""int"",""null""]},{""name"":""message"",""type"":[""string"",""null""]},{""name"":""channel"",""type"":[""string"",""null""]},{""name"":""promoCode"",""type"":[""string"",""null""]},{""name"":""type"",""type"":[""string"",""null""]},{""name"":""isActive"",""type"":""boolean""},{""name"":""propensityScore"",""default"":null,""type"":[""null"",""double""]},{""name"":""sessionId"",""default"":null,""type"":[""null"",""string""]},{""name"":""redeemed"",""default"":null,""type"":[""null"",""boolean""]},{""name"":""clientId"",""default"":null,""type"":[""null"",""string""]},{""name"":""action"",""default"":null,""type"":[""null"",""string""]},{""name"":""title"",""default"":null,""type"":[""null"",""string""]},{""name"":""colour"",""default"":null,""type"":[""null"",""string""]},{""name"":""image"",""default"":null,""type"":[""null"",""string""]},{""name"":""experimentVariantId"",""default"":null,""type"":[""null"",""int""]},{""name"":""inTest"",""default"":null,""type"":[""null"",""boolean""]},{""name"":""hideMessage"",""default"":null,""type"":[""null"",""boolean""]},{""name"":""conversion"",""default"":null,""type"":[""null"",{""type"":""record"",""name"":""Conversion"",""namespace"":"" AO.SCV.MessagingEngine.Events.Schemas"",""fields"":[{""name"":""convertedTimeStamp"",""type"":[""long"",""null""]},{""name"":""orderNumber"",""type"":[""string"",""null""]}]}]}]}");
		private string _visitorId;
		private System.Nullable<int> _messageId;
		private string _message;
		private string _channel;
		private string _promoCode;
		private string _type;
		private bool _isActive;
		private System.Nullable<double> _propensityScore;
		private string _sessionId;
		private System.Nullable<bool> _redeemed;
		private string _clientId;
		private string _action;
		private string _title;
		private string _colour;
		private string _image;
		private System.Nullable<int> _experimentVariantId;
		private System.Nullable<bool> _inTest;
		private System.Nullable<bool> _hideMessage;
		private AO.SCV.MessagingEngine.Events.Schemas.Conversion _conversion;
		public virtual Schema Schema
		{
			get
			{
				return MessagingResult._SCHEMA;
			}
		}
		public string visitorId
		{
			get
			{
				return this._visitorId;
			}
			set
			{
				this._visitorId = value;
			}
		}
		public System.Nullable<int> messageId
		{
			get
			{
				return this._messageId;
			}
			set
			{
				this._messageId = value;
			}
		}
		public string message
		{
			get
			{
				return this._message;
			}
			set
			{
				this._message = value;
			}
		}
		public string channel
		{
			get
			{
				return this._channel;
			}
			set
			{
				this._channel = value;
			}
		}
		public string promoCode
		{
			get
			{
				return this._promoCode;
			}
			set
			{
				this._promoCode = value;
			}
		}
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				this._type = value;
			}
		}
		public bool isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				this._isActive = value;
			}
		}
		public System.Nullable<double> propensityScore
		{
			get
			{
				return this._propensityScore;
			}
			set
			{
				this._propensityScore = value;
			}
		}
		public string sessionId
		{
			get
			{
				return this._sessionId;
			}
			set
			{
				this._sessionId = value;
			}
		}
		public System.Nullable<bool> redeemed
		{
			get
			{
				return this._redeemed;
			}
			set
			{
				this._redeemed = value;
			}
		}
		public string clientId
		{
			get
			{
				return this._clientId;
			}
			set
			{
				this._clientId = value;
			}
		}
		public string action
		{
			get
			{
				return this._action;
			}
			set
			{
				this._action = value;
			}
		}
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		public string colour
		{
			get
			{
				return this._colour;
			}
			set
			{
				this._colour = value;
			}
		}
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				this._image = value;
			}
		}
		public System.Nullable<int> experimentVariantId
		{
			get
			{
				return this._experimentVariantId;
			}
			set
			{
				this._experimentVariantId = value;
			}
		}
		public System.Nullable<bool> inTest
		{
			get
			{
				return this._inTest;
			}
			set
			{
				this._inTest = value;
			}
		}
		public System.Nullable<bool> hideMessage
		{
			get
			{
				return this._hideMessage;
			}
			set
			{
				this._hideMessage = value;
			}
		}
		public AO.SCV.MessagingEngine.Events.Schemas.Conversion conversion
		{
			get
			{
				return this._conversion;
			}
			set
			{
				this._conversion = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
				case 0: return this.visitorId;
				case 1: return this.messageId;
				case 2: return this.message;
				case 3: return this.channel;
				case 4: return this.promoCode;
				case 5: return this.type;
				case 6: return this.isActive;
				case 7: return this.propensityScore;
				case 8: return this.sessionId;
				case 9: return this.redeemed;
				case 10: return this.clientId;
				case 11: return this.action;
				case 12: return this.title;
				case 13: return this.colour;
				case 14: return this.image;
				case 15: return this.experimentVariantId;
				case 16: return this.inTest;
				case 17: return this.hideMessage;
				case 18: return this.conversion;
				default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
				case 0: this.visitorId = (System.String)fieldValue; break;
				case 1: this.messageId = (System.Nullable<int>)fieldValue; break;
				case 2: this.message = (System.String)fieldValue; break;
				case 3: this.channel = (System.String)fieldValue; break;
				case 4: this.promoCode = (System.String)fieldValue; break;
				case 5: this.type = (System.String)fieldValue; break;
				case 6: this.isActive = (System.Boolean)fieldValue; break;
				case 7: this.propensityScore = (System.Nullable<double>)fieldValue; break;
				case 8: this.sessionId = (System.String)fieldValue; break;
				case 9: this.redeemed = (System.Nullable<bool>)fieldValue; break;
				case 10: this.clientId = (System.String)fieldValue; break;
				case 11: this.action = (System.String)fieldValue; break;
				case 12: this.title = (System.String)fieldValue; break;
				case 13: this.colour = (System.String)fieldValue; break;
				case 14: this.image = (System.String)fieldValue; break;
				case 15: this.experimentVariantId = (System.Nullable<int>)fieldValue; break;
				case 16: this.inTest = (System.Nullable<bool>)fieldValue; break;
				case 17: this.hideMessage = (System.Nullable<bool>)fieldValue; break;
				case 18: this.conversion = (AO.SCV.MessagingEngine.Events.Schemas.Conversion)fieldValue; break;
				default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
